name: Update GitHub Snake SVG

on:
  push:
    branches:
      - main
  workflow_dispatch:  # manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: platane/github-contribution-grid-snake@v3
        with:
          github_user_name: your-github-username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Commit SVGs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/*.svg
          git commit -m "Update GitHub contribution snake" || echo "No changes to commit"
          git push
